"""Generate precomputed.js for the demo — full-history equity + benchmark curves for the three
NEW shipped products (DeFi deadband, Meme lightning, Momentum dual-sleeve). The demo's JS slices
these to each timeframe and computes stats via its own portfolioMetrics, so the new cards render
exactly like the live-backtested ones without porting the strategy logic to JS.

Run:  python build_precomputed.py   (writes precomputed.js next to index.html)
Deps: the shipped TradeBot repo + its momentum universe cache (live_state/momentum_universe.pkl).
"""
import json
import pickle
import sys
from pathlib import Path

TB = Path(r"C:\Users\GregoryCaldwell\TradeBot")
sys.path.insert(0, str(TB / "src"))
sys.path.insert(0, str(TB / "scripts"))

import defi_basket as db  # noqa: E402
from defi_basket import (btc_regime, bh_curve, basket_curve, RegimeGated,  # noqa: E402
                         defi_sleeve, CORE, fetch)
from meme_lightning import meme_sleeve, CUTOFF  # noqa: E402
from momentum_dual import build_product  # noqa: E402
from momentum_all import market_bh, START  # noqa: E402

reg = btc_regime(100)


def js_curve(curve):
    return [[t.strftime("%Y-%m-%d"), round(e, 2)] for t, e in curve]


def align_bench(bench_curve, product_curve):
    """Benchmark restricted to the product's timestamps (so slices line up)."""
    m = dict(bench_curve)
    return [(t, m[t]) for t, _ in product_curve if t in m]


# ---- 1) Momentum dual-sleeve (from the disk cache; fast) --------------------
print("building momentum ...")
memes, others = pickle.loads((TB / "live_state" / "momentum_universe.pkl").read_bytes())
alld = {**memes, **others}
mtl = sorted({t for s in alld for t in {b.timestamp for b in alld[s]} if t >= START})
mom = build_product(memes, others, mtl, reg)
mom_bh = align_bench(dict(market_bh(alld, mtl, {s: {b.timestamp: b.close for b in alld[s]} for s in alld})).items(), mom)

# ---- 2) Meme lightning (meme survivors, from cache subset) ------------------
print("building meme lightning ...")
surv = {t: b for t, b in memes.items() if b[0].timestamp <= CUTOFF and len(b) > 400}
ml_common = sorted(set.intersection(*[{x.timestamp for x in surv[t]} for t in surv]))
meme = basket_curve(lambda s: RegimeGated(s, meme_sleeve(s), reg), surv, ml_common, set(ml_common))
meme_bh = bh_curve(surv, ml_common)

# ---- 3) DeFi basket (deadband) — fetch its small universe ------------------
print("building defi (fetching DeFi universe) ...")
defi_data = {s: fetch(s) for s in CORE}
defi_data = {s: b for s, b in defi_data.items() if b}
defi_common = sorted(set.intersection(*[{b.timestamp for b in defi_data[s]} for s in defi_data]))
defi = basket_curve(lambda s: RegimeGated(s, defi_sleeve(s), reg), defi_data, defi_common, set(defi_common))
defi_bh = bh_curve(defi_data, defi_common)

# illustrative activity levels (drive Avg PnL/trade + Trades/week display only)
PAYLOAD = {
    "mom1":  {"name": "Momentum Dual-Sleeve", "equity": js_curve(mom),  "benchmark": js_curve(mom_bh),
              "trades_per_year": 130, "win_rate": 0.50},
    "meme1": {"name": "Meme Lightning",        "equity": js_curve(meme), "benchmark": js_curve(meme_bh),
              "trades_per_year": 18,  "win_rate": 0.44},
    "defi1": {"name": "DeFi Basket",           "equity": js_curve(defi), "benchmark": js_curve(defi_bh),
              "trades_per_year": 34,  "win_rate": 0.55},
}

out = Path(__file__).resolve().parent / "precomputed.js"
out.write_text("/* Auto-generated by build_precomputed.py — validated equity curves for the new products. */\n"
               "window.ITC_PRECOMPUTED = " + json.dumps(PAYLOAD, separators=(",", ":")) + ";\n",
               encoding="utf-8")
for k, v in PAYLOAD.items():
    eq = v["equity"]
    print(f"  {k:<6} {v['name']:<22} {len(eq)} pts  {eq[0][0]}->{eq[-1][0]}  final ${eq[-1][1]:,.0f}")
print(f"wrote {out}")
